#!/bin/bash
# Use this file when building on the actual Pi FOR PRODUCTION
# (does not define DEBUG_FLAG, so strips verbose debugging output)
lex -t PIC.l > PIC.c && gcc -DTEST_BUILD -o PIC PIC.c -ll -lfl -lm -lpthread -lwiringPi
